### ISSUE TITLE
Issue with Bonus Tile Lay in 18AL

### ISSUE THREAD

**Issue by futzy314** [freystef/Rails#15] opened 2016-12-15 21:17 UTC
I am currently part of a 5 player game of 18AL using 2.0 RC1.  Everything has been fine up until now, but I am trying to use the Bonus Tile Lay feature, and the game is getting messed up at that point.  I will attach the save file.  Any way to work around this for now?
[18AL_20161215_2035_Ian.zip](https://github.com/freystef/Rails/files/655837/18AL_20161215_2035_Ian.zip)

**Comment by neutronc** [comment] 2016-12-17 16:14
Thanks for uploading, i will try to find out whats happening,

**Comment by neutronc** [comment] 2016-12-17 16:36
On which field did you place the tile ?

**Comment by neutronc** [comment] 2016-12-17 16:38
OK the confirmation of that Tile Lay goes ballistic.. The game engine doesnt accept a disconnected tile apparently right now... Will have to check.

**Comment by neutronc** [comment] 2016-12-17 17:48
The problem is that the stop on the tile of type "town" isnt properly recognised for whatever reason. This causes the NetworkVertice Routine to bail with a nullpointer exception. Upon tracing back the code i landed in the MapHex.upgrade Method and even here the Tile is not setup correctly. Trying to find out whats happening earlier...

**Comment by neutronc** [comment] 2016-12-17 17:52
My guess is that since the hextile before had no stop the game doesnt translate the necessary information from the tile definition for the upgrade of this hex...

**Comment by neutronc** [comment] 2016-12-17 18:04
No its even simplier the MapHex.upgrade routine doesnt check if theres no stop on the hex before if the new tile brings a stop. Code changed heavily from 1.8 to 2.0 here. So this has to be fixed.

**Comment by erik-vos** [comment] 2016-12-17 18:57
Sorry, I'm not in Rails 2.0 yet.

I suppose this relates to the Lumber Terminal? As this SpecialTile lay 
is configured with 'connected="no"', no connectivity check should be 
done at all, and any attempts to update a connectivity graph (if Rails 
2.0 has such a thing) should gracefully accept the absence of any 
neighbouring stops.

However, from the answers so far I understand that the root problem is 
that the connectivity checking code is not prepared to find a new stop 
on a hex just upgraded where no stop existed before. That's of course a 
different issue that I can shed no light upon.

Op 17-12-2016 om 18:49 schreef Dr. Martin Brumm:

**Comment by neutronc** [comment] 2016-12-18 10:18
Good Morning/evening
i have fixed the error please jump over at sourceforge for the new build.
Regards
Martin

**Closed as completed by neutronc** 2016-12-18 10:18 UTC
Labels: bug
